GLOBALDATA =
[
  {
    "Provider":"APPLE",
    "Provider Country":"US",
    "Vendor Identifier":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "UPC":" ",
    "ISRC":" ",
    "Artist / Show":"Paul Calderon,Maria Di Angelis,Jacqueline Bisset,GÃ©rard Depardieu",
    "Title":"Bem-Vindo a Nova York",
    "Label/Studio/Network":"Belladonna Productions",
    "Product Type Identifier":"D",
    "Units":"1",
    "Royalty Price": "3.49",
    "Download Date (PST)":"2/19/15",
    "Order Id":71000000000000,
    "Postal Code":"95020-210",
    "Customer Identifier":7315403319,
    "Report Date (Local)":"2/19/16",
    "Sale/Return":"S",
    "Customer Currency":"USD",
    "Country Code":"BR",
    "Royalty Currency":"USD",
    "PreOrder":" ",
    "ISAN":" ",
    "Customer Price": "-1.43",
    "Apple Identifier":952289174,
    "CMA":" ",
    "Asset/Content Flavor":"HD",
    "Vendor Offer Code":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "Grid":" ",
    "Promo Code":" ",
    "Parent Identifier":" ",
    "Parent Type Id":"",
    "Attributable Purchase":" ",
    "Primary Genre":"Drama"
  },
  {
    "Provider":"APPLE",
    "Provider Country":"US",
    "Vendor Identifier":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "UPC":" ",
    "ISRC":" ",
    "Artist / Show":"Paul Calderon,Maria Di Angelis,Jacqueline Bisset,GÃ©rard Depardieu",
    "Title":"Bem-Vindo a Nova York",
    "Label/Studio/Network":"Belladonna Productions",
    "Product Type Identifier":"D",
    "Units":1,
    "Royalty Price": 3.49,
    "Download Date (PST)":"1/19/15",
    "Order Id":71000000000000,
    "Postal Code":"95020-210",
    "Customer Identifier":7315403319,
    "Report Date (Local)":"1/19/15",
    "Sale/Return":"S",
    "Customer Currency":"USD",
    "Country Code":"BR",
    "Royalty Currency":"USD",
    "PreOrder":" ",
    "ISAN":" ",
    "Customer Price":6.99,
    "Apple Identifier":952289174,
    "CMA":" ",
    "Asset/Content Flavor":"HD",
    "Vendor Offer Code":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "Grid":" ",
    "Promo Code":" ",
    "Parent Identifier":" ",
    "Parent Type Id":"",
    "Attributable Purchase":" ",
    "Primary Genre":"Drama"
  },
  {
    "Provider":"APPLE",
    "Provider Country":"US",
    "Vendor Identifier":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "UPC":" ",
    "ISRC":" ",
    "Artist / Show":"Paul Calderon,Maria Di Angelis,Jacqueline Bisset,GÃ©rard Depardieu",
    "Title":"Bem-Vindo a Nova York",
    "Label/Studio/Network":"Belladonna Productions",
    "Product Type Identifier":"D",
    "Units":1,
    "Royalty Price":3.49,
    "Download Date (PST)":"1/19/14",
    "Order Id":71000000000000,
    "Postal Code":"95020-210",
    "Customer Identifier":7315403319,
    "Report Date (Local)":"1/19/14",
    "Sale/Return":"S",
    "Customer Currency":"USD",
    "Country Code":"BR",
    "Royalty Currency":"USD",
    "PreOrder":" ",
    "ISAN":" ",
    "Customer Price":-5.50,
    "Apple Identifier":952289174,
    "CMA":" ",
    "Asset/Content Flavor":"HD",
    "Vendor Offer Code":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "Grid":" ",
    "Promo Code":" ",
    "Parent Identifier":" ",
    "Parent Type Id":"",
    "Attributable Purchase":" ",
    "Primary Genre":"Drama"
  },
  {
    "Provider":"APPLE",
    "Provider Country":"US",
    "Vendor Identifier":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "UPC":" ",
    "ISRC":" ",
    "Artist / Show":"Paul Calderon,Maria Di Angelis,Jacqueline Bisset,GÃ©rard Depardieu",
    "Title":"Bem-Vindo a Nova York",
    "Label/Studio/Network":"Belladonna Productions",
    "Product Type Identifier":"D",
    "Units":1,
    "Royalty Price":3.49,
    "Download Date (PST)":"1/19/13",
    "Order Id":71000000000000,
    "Postal Code":"95020-210",
    "Customer Identifier":7315403319,
    "Report Date (Local)":"1/19/14",
    "Sale/Return":"S",
    "Customer Currency":"USD",
    "Country Code":"BR",
    "Royalty Currency":"USD",
    "PreOrder":" ",
    "ISAN":" ",
    "Customer Price":4.99,
    "Apple Identifier":952289174,
    "CMA":" ",
    "Asset/Content Flavor":"HD",
    "Vendor Offer Code":"0511_20141111_SOFA_WELCOMETONEWYORK",
    "Grid":" ",
    "Promo Code":" ",
    "Parent Identifier":" ",
    "Parent Type Id":"",
    "Attributable Purchase":" ",
    "Primary Genre":"Drama"
  },
  {
    "Provider":"APPLE",
    "Provider Country":"US",
    "Vendor Identifier":"0335_20140428_SOFA_CIDADEDEDEUS10ANOSDEPOIS",
    "UPC":" ",
    "ISRC":" ",
    "Artist / Show":"Thiago Martins,Seu Jorge,Roberta Rodrigues,Leandro Firmino da Hora,Jonathan Haagensen,Douglas Silva,Darlan Cunha,Alice Braga,Alexandre Rodrigues",
    "Title":"City of God: 10 Years Later",
    "Label/Studio/Network":"Cavideo ProduÃ§Ãµes",
    "Product Type Identifier":"D",
    "Units":1,
    "Royalty Price":2.79,
    "Download Date (PST)":"1/19/13",
    "Order Id":23000000000000,
    "Postal Code":"94301-1704",
    "Customer Identifier":843001219,
    "Report Date (Local)":"1/19/15",
    "Sale/Return":"S",
    "Customer Currency":"BRL",
    "Country Code":"US",
    "Royalty Currency":"USD",
    "PreOrder":" ",
    "ISAN":" ",
    "Customer Price":3.99,
    "Apple Identifier":914573178,
    "CMA":" ",
    "Asset/Content Flavor":"SD",
    "Vendor Offer Code":"0335_20140428_SOFA_CIDADEDEDEUS10ANOSDEPOIS",
    "Grid":" ",
    "Promo Code":" ",
    "Parent Identifier":" ",
    "Parent Type Id":"",
    "Attributable Purchase":" ",
    "Primary Genre":"Documentary"
  },
  {
    "Provider":"APPLE",
    "Provider Country":"US",
    "Vendor Identifier":"0335_20140428_SOFA_CIDADEDEDEUS10ANOSDEPOIS",
    "UPC":" ",
    "ISRC":" ",
    "Artist / Show":"Thiago Martins,Seu Jorge,Roberta Rodrigues,Leandro Firmino da Hora,Jonathan Haagensen,Douglas Silva,Darlan Cunha,Alice Braga,Alexandre Rodrigues",
    "Title":"City of God: 10 Years Later",
    "Label/Studio/Network":"Cavideo ProduÃ§Ãµes",
    "Product Type Identifier":"D",
    "Units":1,
    "Royalty Price":2.79,
    "Download Date (PST)":"1/19/13",
    "Order Id":23000000000000,
    "Postal Code":"94301-1704",
    "Customer Identifier":843001219,
    "Report Date (Local)":"1/19/15",
    "Sale/Return":"S",
    "Customer Currency":"BRL",
    "Country Code":"US",
    "Royalty Currency":"USD",
    "PreOrder":" ",
    "ISAN":" ",
    "Customer Price":3.99,
    "Apple Identifier":914573178,
    "CMA":" ",
    "Asset/Content Flavor":"SD",
    "Vendor Offer Code":"0335_20140428_SOFA_CIDADEDEDEUS10ANOSDEPOIS",
    "Grid":" ",
    "Promo Code":" ",
    "Parent Identifier":" ",
    "Parent Type Id":"",
    "Attributable Purchase":" ",
    "Primary Genre":"Documentary"
  }
]
